import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import fs from "fs/promises";
import path from "path";
import { cosineSimilarity, embedTexts } from "../../../lib/embeddings";
import { authOptions } from "../../../lib/auth";

type Source={id:string;title:string;url:string;snippet:string;type:"Wikipedia"|"arXiv"|"OpenAlex"|"Knowledge Base";score?:number};
type KBChunk={id:string;documentId:string;documentName:string;text:string;embedding?:number[];ownerEmail?:string};
type KBStore={documents:any[];chunks:KBChunk[]};
type HistoryItem={id:string;userEmail:string;query:string;answer:string;sources:Source[];createdAt:string};
const DATA_FILE=path.join(process.cwd(),"data","knowledge-base.json");
const HISTORY_FILE=path.join(process.cwd(),"data","history.json");
const AI_TIMEOUT_MS=25000;
function normalize(text:string){return text.toLowerCase().replace(/[^a-z0-9\s-]/g," ").replace(/\s+/g," ").trim();}
function queryTerms(query:string){const stop=new Set(["the","and","for","with","what","how","why","are","is","of","to","in","on","a","an","compare","comparison","explain","tell","about","according","document","uploaded","file","my","does","do","can","please","say","says","from","this","that","me","give","show","would","could","should","your","you","into","than","using","use","used","based","also","their","they","them","it","its","which"]);return[...new Set(normalize(query).split(" ").filter(w=>w.length>2&&!stop.has(w)))];}
function variants(term:string){const s=new Set([term]);if(term.endsWith("ing")&&term.length>5)s.add(term.slice(0,-3));if(term.endsWith("s")&&term.length>4)s.add(term.slice(0,-1));if(term.endsWith("ed")&&term.length>5)s.add(term.slice(0,-2));return[...s];}
function matches(text:string,term:string){return variants(term).some(v=>text.includes(v));}
function score(query:string,s:Source){const terms=queryTerms(query),title=normalize(s.title),text=normalize(`${s.title} ${s.snippet}`);let value=0,matched=0;for(const t of terms){if(title.includes(t)){value+=12;matched++;}else if(matches(text,t)){value+=4;matched++;}}if(text.includes(normalize(query)))value+=14;value+=(matched/Math.max(terms.length,1))*12;if(s.type==="Knowledge Base")value+=35;if(s.type==="arXiv")value+=1.5;return value;}
function rank(query:string,candidates:Source[],strongKB=false){const seen=new Set<string>();return candidates.map(s=>({...s,score:score(query,s)})).filter(s=>{const key=`${normalize(s.title)}|${s.url}|${normalize(s.snippet).slice(0,160)}`;if(seen.has(key))return false;seen.add(key);const terms=queryTerms(query),text=normalize(`${s.title} ${s.snippet}`),matched=terms.filter(t=>matches(text,t)).length;if(s.type==="Knowledge Base")return matched>0||(s.score??0)>=1;if(strongKB)return matched>=Math.min(2,terms.length)&&(matched/Math.max(terms.length,1))>=.35;return matched>0&&(s.score??0)>=4;}).sort((a,b)=>(b.score??0)-(a.score??0)).slice(0,10).map((s,i)=>({...s,id:`S${i+1}`}));}
async function getStore():Promise<KBStore>{try{return JSON.parse(await fs.readFile(DATA_FILE,"utf8")) as KBStore;}catch{return{documents:[],chunks:[]};}}
async function writeStore(store:KBStore){await fs.mkdir(path.dirname(DATA_FILE),{recursive:true});await fs.writeFile(DATA_FILE,JSON.stringify(store,null,2),"utf8");}
async function getEmail(){const session=await getServerSession(authOptions);return session?.user?.email?.toLowerCase()||null;}
async function ensureEmbeddings(store:KBStore){const missing=store.chunks.filter(c=>!Array.isArray(c.embedding)||!c.embedding.length);if(!missing.length)return store;try{const vectors=await embedTexts(missing.map(c=>c.text));const map=new Map(missing.map((c,i)=>[c.id,vectors[i]]));store.chunks=store.chunks.map(c=>map.has(c.id)?{...c,embedding:map.get(c.id)}:c);await writeStore(store);}catch(e){console.warn("Embedding backfill skipped",e);}return store;}
async function retrieveKB(query:string,email:string){const store=await ensureEmbeddings(await getStore());const visible=store.chunks.filter(c=>!c.ownerEmail||c.ownerEmail===email);if(!visible.length)return[];let qv:number[]|null=null;try{qv=(await embedTexts([query]))[0]??null;}catch(e){console.warn("Semantic query embedding unavailable",e);}const terms=queryTerms(query);return visible.map(c=>{const text=normalize(c.text),title=normalize(c.documentName);const lexical=terms.reduce((n,t)=>n+(matches(`${title} ${text}`,t)?1:0),0);const semantic=qv&&c.embedding?cosineSimilarity(qv,c.embedding):0;return{c,score:semantic*100+lexical*6,lexical,semantic};}).filter(x=>x.lexical>0||x.semantic>=.25).sort((a,b)=>b.score-a.score).slice(0,5).map(x=>({id:"",title:x.c.documentName,url:`/api/knowledge/file/${x.c.documentId}`,snippet:x.c.text,type:"Knowledge Base" as const,score:x.score}));}
function abstractText(index:Record<string,number[]>|undefined){if(!index)return"";const words:string[]=[];for(const[w,pos]of Object.entries(index))for(const p of pos)words[p]=w;return words.filter(Boolean).join(" ").slice(0,1400);}
async function publicSources(query:string){const terms=queryTerms(query);const technical=/\b(ai|ml|machine learning|deep learning|llm|rag|nlp|computer vision|neural|transformer|reinforcement learning|data science|cybersecurity|software engineering|algorithm)\b/i.test(query);const jobs:Promise<Source[]>[]=[(async()=>{try{const u=`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(query)}&format=json&srlimit=8&origin=*`;const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)return[];const d=await r.json();return(d?.query?.search??[]).map((x:any)=>({id:"",title:x.title,url:`https://en.wikipedia.org/wiki/${encodeURIComponent(x.title.replace(/ /g,"_"))}`,snippet:String(x.snippet??"").replace(/<[^>]+>/g,""),type:"Wikipedia" as const}));}catch{return[];}})(),(async()=>{try{const u=`https://api.openalex.org/works?search=${encodeURIComponent(terms.length?terms.join(" "):query)}&per-page=8&sort=relevance_score:desc`;const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)return[];const d=await r.json();return(d?.results??[]).map((x:any)=>({id:"",title:x.display_name??"Untitled research work",url:x.doi||x.primary_location?.landing_page_url||x.id,snippet:abstractText(x.abstract_inverted_index)||`${x.publication_year??""} · Scholarly work · ${x.primary_location?.source?.display_name??"OpenAlex"}`,type:"OpenAlex" as const}));}catch{return[];}})()];if(technical)jobs.push((async()=>{try{const q=terms.length?terms.map(t=>`all:${t}`).join(" AND "):`all:${query}`;const u=`https://export.arxiv.org/api/query?search_query=${encodeURIComponent(q)}&start=0&max_results=8&sortBy=relevance&sortOrder=descending`;const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)return[];const xml=await r.text(),entries=xml.match(/<entry>[\s\S]*?<\/entry>/g)??[];return entries.map(e=>{const title=e.match(/<title>([\s\S]*?)<\/title>/)?.[1]?.replace(/\s+/g," ").trim(),summary=e.match(/<summary>([\s\S]*?)<\/summary>/)?.[1]?.replace(/\s+/g," ").trim(),id=e.match(/<id>([\s\S]*?)<\/id>/)?.[1]?.trim();return title&&id?{id:"",title,url:id,snippet:summary??"",type:"arXiv" as const}:null;}).filter(Boolean) as Source[];}catch{return[];}})());const results=await Promise.allSettled(jobs);return results.flatMap(r=>r.status==="fulfilled"?r.value:[]);}
function fallback(query:string,sources:Source[]){if(!sources.length)return`## Executive Summary\n\nI could not retrieve relevant evidence for **${query}**.`;return`## Executive Summary\n\nHere is a source-backed research brief for **${query}**.\n\n## Key Findings\n\n${sources.slice(0,6).map(s=>`- **${s.title}** — ${s.snippet.slice(0,450)} [${s.id}]`).join("\n")}\n\n## Important Insights\n\n- Private Knowledge Base evidence is semantically searched and prioritized when relevant.\n- Public evidence is filtered for meaningful overlap.\n\n## Limitations\n\n- Verify important claims against the linked source.\n\n## Further Research\n\nOpen the highest-ranked sources and refine the query.`;}
async function synthesize(apiKey:string,query:string,context:string,citations:boolean){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),AI_TIMEOUT_MS);try{const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`,"HTTP-Referer":"http://localhost:3000","X-Title":"Research Command Center"},signal:controller.signal,body:JSON.stringify({model:"openai/gpt-oss-20b:free",temperature:.2,max_tokens:1800,messages:[{role:"system",content:`You are a careful general-purpose research assistant. Use ONLY the retrieved evidence supplied by the application. Never invent studies, statistics, authors, dates or citations. If evidence is insufficient, say so. Return concise Markdown with Executive Summary, Key Findings, Important Insights, Limitations, and Further Research. ${citations?"Every factual claim from evidence must include [S1]-style source IDs.":"Do not add inline source IDs."} If a private Knowledge Base source directly answers the question, treat it as primary evidence and say that the answer uses the uploaded document.`},{role:"user",content:`Research question:\n${query}\n\nRetrieved evidence:\n${context}\n\nWrite the research brief.`}]})});const text=await r.text();if(!r.ok)throw new Error(`OpenRouter error (${r.status}): ${text.slice(0,500)}`);const data=JSON.parse(text);return data?.choices?.[0]?.message?.content||null;}finally{clearTimeout(timeout);}}
async function saveHistory(email:string,query:string,answer:string,sources:Source[]){try{let items:HistoryItem[]=[];try{items=JSON.parse(await fs.readFile(HISTORY_FILE,"utf8")) as HistoryItem[];}catch{}items.unshift({id:`research_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,userEmail:email,query,answer,sources:sources.map(({id,title,url,snippet,type})=>({id,title,url,snippet,type})),createdAt:new Date().toISOString()});await fs.mkdir(path.dirname(HISTORY_FILE),{recursive:true});await fs.writeFile(HISTORY_FILE,JSON.stringify(items.slice(0,250),null,2),"utf8");}catch(e){console.warn("History save skipped",e);}}
export async function POST(request:NextRequest){try{const email=await getEmail();if(!email)return NextResponse.json({error:"Unauthorized"},{status:401});const apiKey=process.env.OPENROUTER_API_KEY;if(!apiKey)return NextResponse.json({error:"OPENROUTER_API_KEY is missing. Add it to .env.local and restart the server."},{status:500});const body=await request.json(),query=body.query;const useKB=body.grounding!==false;const citations=body.citations!==false;if(!query||typeof query!=="string")return NextResponse.json({error:"A research query is required."},{status:400});const kb=useKB?await retrieveKB(query,email):[];const publicEvidence=await publicSources(query);const candidates=[...kb,...publicEvidence];const strongKB=kb.length>0&&(kb[0].score??0)>=35;const sources=rank(query,candidates,strongKB);const context=sources.length?sources.map(s=>`[${s.id}] ${s.title}\nSource type: ${s.type}\nURL: ${s.url||"Uploaded document"}\nEvidence: ${s.snippet}`).join("\n\n"):"No relevant sources were retrieved.";let answer:string,usedFallback=false;try{answer=await synthesize(apiKey,query,context,citations);if(!answer)throw new Error("No AI answer returned");}catch(e){console.warn("AI synthesis unavailable; using retrieval fallback",e);answer=fallback(query,sources);usedFallback=true;}await saveHistory(email,query,answer,sources);return NextResponse.json({success:true,query,answer,sources,sourceCount:sources.length,usedFallback,researchMode:useKB?"semantic-rag":"public-research"});}catch(error){console.error("Research API error",error);return NextResponse.json({error:error instanceof Error?error.message:"Unexpected server error."},{status:500});}}
