"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, ExternalLink, FileSearch, FolderOpen, LayoutDashboard, Plus, Search, Settings, ShieldCheck, Sparkles, Target, Upload, Users, Trash2 } from "lucide-react";

const examples = ["Latest developments in electric vehicles", "Compare RAG architectures for enterprise AI", "History and impact of the internet", "Best practices for cybersecurity awareness"];
type Source = { id: string; title: string; url: string; snippet: string; type: "Wikipedia" | "arXiv" | "OpenAlex" | "Knowledge Base" };
type Session = { id: number; query: string; sources: number };
type KBDoc = { id: string; name: string; type: string; size: number; createdAt: string; chunks: number };
const navItems = [{ id: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { id: "research", label: "Research", icon: Sparkles }, { id: "projects", label: "Projects", icon: FolderOpen }, { id: "knowledge", label: "Knowledge Base", icon: BookOpen }, { id: "history", label: "History", icon: Clock3 }, { id: "collaborators", label: "Collaborators", icon: Users }, { id: "settings", label: "Settings", icon: Settings }];

export default function Home() {
  const [active, setActive] = useState("dashboard"); const [query, setQuery] = useState(""); const [running, setRunning] = useState(false); const [message, setMessage] = useState(""); const [sources, setSources] = useState<Source[]>([]); const [sessions, setSessions] = useState<Session[]>([]); const [projectName, setProjectName] = useState(""); const [projects, setProjects] = useState(["Enterprise AI Research", "RAG Evaluation"]); const [inviteEmail, setInviteEmail] = useState(""); const [invited, setInvited] = useState<string[]>([]); const [grounding, setGrounding] = useState(true); const [citations, setCitations] = useState(true); const [kbDocs, setKbDocs] = useState<KBDoc[]>([]); const [kbChunks, setKbChunks] = useState(0); const [uploading, setUploading] = useState(false); const [uploadMessage, setUploadMessage] = useState("");

  const loadKnowledgeBase = async () => { try { const response = await fetch("/api/knowledge", { cache: "no-store" }); const data = await response.json(); if (response.ok) { setKbDocs(data.documents ?? []); setKbChunks(data.chunkCount ?? 0); } } catch (error) { console.error("Knowledge Base load error:", error); } };
  useEffect(() => { loadKnowledgeBase(); }, []);

  const runResearch = async () => { if (!query.trim() || running) return; setRunning(true); setActive("research"); setMessage("Searching your Knowledge Base and public research sources..."); setSources([]); try { const response = await fetch("/api/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: query.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || `API request failed (${response.status})`); setMessage(data.answer); setSources(data.sources ?? []); setSessions((current) => [{ id: Date.now(), query: query.trim(), sources: data.sources?.length ?? 0 }, ...current]); } catch (error) { console.error("Research error:", error); setMessage(error instanceof Error ? `Error: ${error.message}` : "Something went wrong while generating the research."); } finally { setRunning(false); } };
  const createProject = () => { if (!projectName.trim()) return; setProjects((current) => [projectName.trim(), ...current]); setProjectName(""); };
  const invite = () => { if (!inviteEmail.trim()) return; setInvited((current) => [...current, inviteEmail.trim()]); setInviteEmail(""); };
  const startNewResearch = () => { setQuery(""); setMessage(""); setSources([]); setActive("research"); };

  const handleUpload = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); if (!files.length) return; setUploading(true); setUploadMessage("Extracting text and indexing documents..."); for (const file of files) { const form = new FormData(); form.append("file", file); try { const response = await fetch("/api/knowledge", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Upload failed"); setUploadMessage(data.message); } catch (error) { setUploadMessage(error instanceof Error ? `Error: ${error.message}` : "Upload failed."); } } await loadKnowledgeBase(); setUploading(false); event.target.value = ""; };
  const deleteDocument = async (documentId: string) => { if (!confirm("Delete this document from the Knowledge Base?")) return; await fetch("/api/knowledge", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ documentId }) }); await loadKnowledgeBase(); };

  const renderResearch = () => (<><div className="card research-card"><div className="cardhead"><div className="title-with-icon"><Sparkles size={18} /><div><h2>Start Research</h2><p>Search your private documents plus general and academic knowledge, then generate a grounded research brief.</p></div></div><span className="badge">Web + Academic + Private RAG</span></div><div className="searchbox"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && runResearch()} placeholder="Ask anything... e.g. What does my document say about regenerative braking?" /><button className="primary" onClick={runResearch} disabled={running}>{running ? "Researching..." : "Research"}<Sparkles size={14} /></button></div><div className="samples">{examples.map((example) => <button className="sample" key={example} onClick={() => setQuery(example)}>{example}</button>)}</div><div style={{ marginTop: 13, display: "flex", alignItems: "center", gap: 6, color: "#777", fontSize: 10 }}><ShieldCheck size={13} />{grounding ? "Private + public source grounding active" : "Source grounding disabled"}</div>{message && <div className="answer">{message}</div>}</div>{sources.length > 0 && <div className="card section-card"><div className="cardhead"><div><h2>Retrieved Sources</h2><p>Evidence used to ground this response.</p></div><span className="count-pill">{sources.length} sources</span></div><div className="source-list">{sources.map((source) => <div className="source-item" key={source.id}><div className="source-id">{source.id}</div><div className="source-content"><strong>{source.title}</strong><span>{source.type} · {source.snippet}</span></div>{source.url ? <a href={source.url} target="_blank" rel="noreferrer" className="source-link">Open <ExternalLink size={13} /></a> : <span className="source-link">Private document</span>}</div>)}</div></div>}</>);

  const renderPipeline = () => (<div className="card side-card"><div className="cardhead"><h2>Research Pipeline</h2><span className="status">Ready</span></div><div className="pipeline-step"><div className="step-icon"><FileSearch size={14} /></div><div><strong>1. Query Analysis</strong><span>Understand and structure the question</span></div><CheckCircle2 className="check" size={15} /></div><div className="pipeline-step"><div className="step-icon"><Search size={14} /></div><div><strong>2. Source Retrieval</strong><span>Private documents + Wikipedia + OpenAlex + arXiv</span></div><CheckCircle2 className="check" size={15} /></div><div className="pipeline-step"><div className="step-icon"><Sparkles size={14} /></div><div><strong>3. RAG Synthesis</strong><span>Ground the response in retrieved evidence</span></div><CheckCircle2 className="check" size={15} /></div><div className="pipeline-step"><div className="step-icon"><Target size={14} /></div><div><strong>4. Citation Mapping</strong><span>Attach source IDs to factual claims</span></div><CheckCircle2 className="check" size={15} /></div><div className="progress"><i /></div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 7, color: "#777", fontSize: 9 }}><span>Pipeline ready</span><strong>100%</strong></div></div>);
  const renderKnowledgeMini = () => (<div className="card side-card"><div className="cardhead"><div><h2>Knowledge Base</h2><p>Your private research library</p></div><Upload size={15} /></div><div className="knowledge-row"><span>Documents</span><strong>{kbDocs.length}</strong></div><div className="knowledge-row"><span>Searchable chunks</span><strong>{kbChunks}</strong></div><button className="side-link" onClick={() => setActive("knowledge")}>Manage Knowledge Base <ArrowRight size={13} /></button></div>);
  const renderDashboard = () => (<><div className="stats"><div className="card stat"><div className="stat-icon"><Search size={18} /></div><div><small>Research Sessions</small><strong>{24 + sessions.length}</strong><span>Workspace activity</span></div></div><div className="card stat"><div className="stat-icon"><BookOpen size={18} /></div><div><small>Sources Retrieved</small><strong>{sources.length}</strong><span>Current research</span></div></div><div className="card stat"><div className="stat-icon"><ShieldCheck size={18} /></div><div><small>Knowledge Chunks</small><strong>{kbChunks}</strong><span>Searchable private evidence</span></div></div></div><div className="grid"><section>{renderResearch()}</section><aside className="side">{renderPipeline()}{renderKnowledgeMini()}</aside></div></>);
  const renderProjects = () => (<div className="card section-card large-section"><div className="cardhead"><div><h2>Projects</h2><p>Organize research sessions into focused workspaces.</p></div></div><div className="inline-form"><input value={projectName} onChange={(e) => setProjectName(e.target.value)} placeholder="New project name" onKeyDown={(e) => e.key === "Enter" && createProject()} /><button className="primary" onClick={createProject}><Plus size={15} />Create Project</button></div><div className="project-grid">{projects.map((project) => <button className="project-card" key={project} onClick={() => { setQuery(project); setActive("research"); }}><FolderOpen size={20} /><strong>{project}</strong><span>Open research workspace <ArrowRight size={13} /></span></button>)}</div></div>);
  const renderKnowledge = () => (<div className="card section-card large-section"><div className="cardhead"><div><h2>Knowledge Base</h2><p>Upload documents, extract their text, split them into searchable chunks and use those chunks as private RAG evidence.</p></div><label className="upload-button"><Upload size={15} />{uploading ? "Indexing..." : "Upload documents"}<input type="file" multiple accept=".pdf,.txt,.md" onChange={handleUpload} disabled={uploading} /></label></div><div className="knowledge-summary"><div><strong>{kbDocs.length}</strong><span>Documents</span></div><div><strong>{kbChunks}</strong><span>Searchable chunks</span></div><div><strong>Private</strong><span>Local knowledge</span></div></div>{uploadMessage && <div className="upload-message">{uploadMessage}</div>}<div className="file-list">{kbDocs.length ? kbDocs.map((doc) => <div className="file-row" key={doc.id}><BookOpen size={16} /><div><strong>{doc.name}</strong><span>{doc.chunks} searchable chunks · {Math.round(doc.size / 1024)} KB</span></div><span className="status">Indexed</span><button className="icon-button" onClick={() => deleteDocument(doc.id)} title="Delete"><Trash2 size={15} /></button></div>) : <div className="empty"><BookOpen size={26} /><strong>No documents indexed yet</strong><span>Upload the dummy PDF and then ask a question about its contents.</span></div>}</div></div>);
  const renderHistory = () => (<div className="card section-card large-section"><div className="cardhead"><div><h2>Research History</h2><p>Your research sessions from this browser.</p></div></div>{sessions.length === 0 ? <div className="empty"><Clock3 size={26} /><strong>No sessions yet</strong><span>Run your first research query and it will appear here.</span><button className="secondary" onClick={startNewResearch}>Start Research</button></div> : <div className="history-list">{sessions.map((session) => <button className="history-row" key={session.id} onClick={() => { setQuery(session.query); setActive("research"); }}><Clock3 size={16} /><div><strong>{session.query}</strong><span>{session.sources} sources · Open session</span></div><ArrowRight size={15} /></button>)}</div>}</div>);
  const renderCollaborators = () => (<div className="card section-card large-section"><div className="cardhead"><div><h2>Collaborators</h2><p>Invite people to work on research projects.</p></div></div><div className="inline-form"><input value={inviteEmail} onChange={(e) => setInviteEmail(e.target.value)} placeholder="colleague@example.com" type="email" onKeyDown={(e) => e.key === "Enter" && invite()} /><button className="primary" onClick={invite}><Users size={15} />Invite</button></div><div className="member-list"><div className="member"><div className="member-avatar">CD</div><div><strong>Carsyn D.</strong><span>Owner · Researcher</span></div><span className="status">Active</span></div>{invited.map((email) => <div className="member" key={email}><div className="member-avatar">{email[0].toUpperCase()}</div><div><strong>{email}</strong><span>Research collaborator</span></div><span className="status">Invited</span></div>)}</div></div>);
  const renderSettings = () => (<div className="card section-card large-section"><div className="cardhead"><div><h2>Settings</h2><p>Application preferences and research configuration.</p></div></div><div className="settings-list"><button className="setting" onClick={() => setGrounding(!grounding)}><div><strong>Research grounding</strong><span>Use retrieved sources before generating responses.</span></div><span className="toggle on">{grounding ? "ON" : "OFF"}</span></button><button className="setting" onClick={() => setCitations(!citations)}><div><strong>Source citations</strong><span>Attach source IDs to factual claims.</span></div><span className="toggle on">{citations ? "ON" : "OFF"}</span></button><div className="setting"><div><strong>Workspace</strong><span>Research Command Center · v1.5</span></div><span className="setting-value">Local</span></div></div></div>);
  const title = navItems.find((item) => item.id === active)?.label ?? "Dashboard";
  return <div className="page"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><strong>Research Command</strong><span>Center</span></div></div><nav className="nav">{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={active === id ? "active" : ""} onClick={() => setActive(id)}><Icon size={17} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="system"><i />System Online</div><span>v1.5.0 · Built with Next.js</span></div></aside><main className="main"><header className="header"><div><div className="eyebrow">Workspace / {title}</div><h1>{active === "dashboard" ? "Research Command Center" : title}</h1><p className="subtitle">Research almost anything using retrieved evidence, academic literature and your private documents.</p></div><div className="avatar">CD</div></header>{active === "dashboard" && renderDashboard()}{active === "research" && renderResearch()}{active === "projects" && renderProjects()}{active === "knowledge" && renderKnowledge()}{active === "history" && renderHistory()}{active === "collaborators" && renderCollaborators()}{active === "settings" && renderSettings()}</main></div>;
}
